### PR TITLE
Added Slide Show and image upload box, along titles for each.

### PR DESCRIPTION
**Pull request by DeannaMix**
## Description
I added a slideshow to the fashion page.

## Related Issue
New feature for ticket #6 . The user will see the slideshow when they enter the page.

## Motivation and Context
This allows the user to see the jort port slideshow.

## How Can This Be Tested?
Yes, there is a filler image in the Jort Port fashion slideshow. With later changes, the user will be able to upload their own photos into the slideshow.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by bandstrar — APPROVED** [review]
Working as intended

**Review by chris-calhoun — CHANGES_REQUESTED** [review]
I think the code in the index.html got deleted during your last pull of master.

**Review by bandstrar — APPROVED** [review]
👍

**Review by chris-calhoun — APPROVED** [review]
👍

**Pull request merged**
